### ISSUE TITLE
CORS problems when using post method

### ISSUE THREAD

**Issue by NovaNemesis99** [bluecoder24/dhbw-dbek-todo-core#18]
fixed by adding 'Header set Access-Control-Allow-Headers *' to .htaccess

**Comment by bluecoder24** [comment]
Updated .htaccess, please give feedback

**Comment by NovaNemesis99** [comment]
now working when using the methods wildcard * since the prposed solution mentioned in #20 is breaking everything

**Comment by bluecoder24** [comment]
is fixed with *

**Comment by NovaNemesis99** [comment]
is working
