### ISSUE TITLE
Routes for post methods not working

### ISSUE THREAD

**Issue by NovaNemesis99** [bluecoder24/dhbw-dbek-todo-core#19]
When sending post requests errors are thrown even though routes are correct -> no adding of new data possible.
Request answer can be seen in the attached screenshot.
![grafik](https://user-images.githubusercontent.com/64359919/85929985-180a2500-b8b9-11ea-9002-c6c01618ec31.png)

**Comment by bluecoder24** [comment]
I couldn't reproduce this at the moment, with Postman all POST routes are working, both for new data and updating.

**Comment by NovaNemesis99** [comment]
I will look into it, maybe there are some problems concerning data models

**Comment by NovaNemesis99** [comment]
fixed by removing the highlighted / in the route. This caused the problems. The / was an artifact from copying routes with url parameters instead of request bodies, fixed for the other post request url as well
return this.http.post('http://localhost/dhbw-dbek-todo-core-dev/public/index.php/addOrUpdateTask **/**', task).pipe(catchError(this.handleError.bind(this)));
