### ISSUE TITLE
CORS problems when using delete request

### ISSUE THREAD

**Issue by NovaNemesis99** [bluecoder24/dhbw-dbek-todo-core#20]
fixed by adding 'Header set Access-Control-Allow-Methods *' in .htaccess

**Comment by bluecoder24** [comment]
I propose trying with "Header set Access-Control-Allow-Methods: POST, GET, DELETE, OPTIONS", because I don't like opening up for all methods.

**Comment by NovaNemesis99** [comment]
Seem reasonable, I'm fine with that

**Comment by NovaNemesis99** [comment]
using your solution instead of Header set Access-Control-Allow-Methods * breaks everything for some reason, even normal get requests stop working even though they are listed as allowed method

**Comment by NovaNemesis99** [comment]
fixed with the solution of #18
