### ISSUE TITLE
Close tab after populating db

### ISSUE THREAD

**Issue by NovaNemesis99** [bluecoder24/dhbw-dbek-todo-core#21]
It would be nice if the browser tab of initDB.php would close itself after creating the example data, so that the user doesn't need to do it.

**Comment by bluecoder24** [comment]
This seems to be impossible, look here: https://stackoverflow.com/questions/19761241/window-close-and-self-close-do-not-close-the-window-in-chrome
I'll add a sucess message to the script or maybe print the created data.

**Comment by NovaNemesis99** [comment]
That's ok, definitly better than just showing an empty page.
