### ISSUE TITLE
Adjust sample data

### ISSUE THREAD

**Issue by NovaNemesis99** [bluecoder24/dhbw-dbek-todo-core#25]
Sample data should be adjusted so that it can be displayed better. Relevant: https://github.com/NovaNemesis99/DHBW-TODO-WebApp/issues/3#issue-647311382 the frontend is now set up for displaying duedates in the format that is used by the datpicker input when creating new tasks. Therefore the current sample data duedates are broken. Possible solution after creating a clean new database create all sample data with the frontend an then export this data for submission. Maybe add wontfix label too.

**Comment by bluecoder24** [comment]
Updated the date format in initDB, looks good now.
