### ISSUE TITLE
Please separate backend into logical parts

### ISSUE THREAD

**Issue by mschweikert** [bluecoder24/dhbw-dbek-todo-core#32]
Having the implementation of the slim framework, the routes, the backend logic and the database access in the same file (index.php) is outdated.

For tips see:
https://github.com/odan/slim4-skeleton

**Comment by bluecoder24** [comment]
According to Mr. Perschkes requirements (http://www.perschke.info/dhbwvs20200420/40_REST/41_RestMitSlim.pdf, page 6) there are no additional files needed: 
_Wie Sie erfahren haben, bildet die Datei „index.php“ den zentralen Einstiegspunkt. In der Regel
werden wir keine weiteren PHP-Dateien benötigen!!! Wir schauen uns den aktuellen Inhalt der Datei
an und ergänzen diesen kontinuierlich._
